### ISSUE TITLE
Label Font and Background color is the same in KPI Window

### ISSUE THREAD

**Issue by williamwmy** [oslokommune/okr-tracker#345]
It is impossible to read the Label for a textbox and Button when adding KPI. The color and the background has the same color.

Reproduction step:
- Go to a team
- Press "Legg til"
- Choose "KPI-er" tab
- Press "Legg til KPI"

Tested in both Chrome and Safari and in both Blue and Green theme.

<img width="547" alt="image" src="https://user-images.githubusercontent.com/459803/159942772-db017e05-23f6-4ef8-a9fb-27753429366c.png">

**Comment by annemerete** [comment]
Fixed in #348
