### ISSUE TITLE
Changing "Periode" in Objectives doesn't enable the save button.

### ISSUE THREAD

**Issue by williamwmy** [oslokommune/okr-tracker#365]
**Changing "Periode" in Objectives doesn't enable the save button.**

**Reproduction Step:**

1. Go to a Objective
2. Press "Endre nøkkelresultater"
3. Choose the tab "Mål og nøkkelresultater"
4. Choose one existing Objective
5. Try to change "Periode"

Result: Can't save it, the save button is disabled

Desired outcome: Save button is enabled to allow the objective to be saved.

Walkaround: Change something in "Navn" og "Beskrivelse" and then hit save.

![image](https://user-images.githubusercontent.com/459803/169231685-845df808-4cfa-471f-a5e2-5211e94e2b0b.png)

**Comment by simenheg** [comment]
Thanks for the report, @williamwmy!

This issue appears to have been fixed in the latest release, but please reopen if you should find that's not the case. :)
