### ISSUE TITLE
Bug: Returning from the objective page to the overview page only shows one objective

### ISSUE THREAD

**Issue by helgeloken** [oslokommune/okr-tracker#672]
Steps to reproduce

1. Click an objective 
2. Go back to the overview where all the objectives should be show - either by pressing the back button or by pressing "Mål and nøkkelresultater"

Instead of showing all objectives, only the objective you visited is shown. You have to hit refresh to get all the objectives.

**Comment by simenheg** [comment]
Thanks, reproduces here. A fix is in the works. :)

**Comment by simenheg** [comment]
> A fix is in the works. :)

Or so I thought! This bug is elusive, it seems to happen around 1/10 of the time for me. We'll continue trying to pin it down.

PRs welcome meanwhile if you manage to catch the bug. ;)

**Comment by helgeloken** [comment]
For me it happens 10/10... Is there anything I can do to help reproduce? Could it be because I'm an admin? 

Unfortunately I'm not a developer, so I can't help with the actual code.

**Comment by simenheg** [comment]
Should be fixed by https://github.com/oslokommune/okr-tracker/pull/674. ;)

**Comment by helgeloken** [comment]
Great! We will test it as soon as it gets merged into master. Thank you.
