### ISSUE TITLE
The login instructions for demo do not work

### ISSUE THREAD

**Issue by pranjalrajput** [oslokommune/okr-tracker#985]
Hey folks,

I am trying to login to demo url using the details given in readme file.
It doesnt seem to work.
Has something changed ?
![Uploading Screenshot 2024-08-11 at 8.33.01 pm.png…]()

**Comment by pranjalrajput** [comment]
![Screenshot 2024-08-11 at 8 33 01 pm](https://github.com/user-attachments/assets/8853f17d-7d79-4b3b-9d19-117e3b8415fb)

**Comment by simenheg** [comment]
Hi @pranjalrajput, that was strange.

I tested it now with the username and password from the README and it worked for me. Could you try again?

**Comment by simenheg** [comment]
Closing this, please reopen if it's still a problem.
